# Generated by Django 5.1.4 on 2025-01-19 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('occupation', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=500)),
                ('pic', models.CharField(max_length=200)),
            ],
        ),
    ]
