# Generated by Django 5.1.4 on 2025-01-19 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hallwaywebsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimony',
            name='pic',
            field=models.CharField(max_length=180),
        ),
    ]
