# Generated by Django 5.1.5 on 2025-01-26 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hallwaywebsite', '0002_alter_testimony_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=220)),
                ('header_img', models.CharField(max_length=120)),
            ],
        ),
    ]
