# Generated by Django 5.1.5 on 2025-01-26 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hallwaywebsite', '0003_blogarticle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(max_length=200)),
                ('twitter', models.CharField(max_length=400)),
                ('linkedin', models.CharField(max_length=500)),
                ('instagram', models.CharField(max_length=500)),
                ('pic', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.AlterField(
            model_name='blogarticle',
            name='header_img',
            field=models.ImageField(upload_to='article_imgs'),
        ),
    ]
