# Generated by Django 5.1.5 on 2025-01-27 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hallwaywebsite', '0004_team_alter_blogarticle_header_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=220)),
                ('header_img', models.ImageField(upload_to='article_imgs')),
            ],
        ),
        migrations.CreateModel(
            name='HallwayEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=220)),
                ('location', models.CharField(max_length=220)),
                ('header_img', models.ImageField(upload_to='hallway_events')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TopPerformingProfessionals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=220)),
                ('name_of_person', models.CharField(max_length=120)),
                ('profile_picture', models.ImageField(upload_to='profile_pics')),
            ],
        ),
        migrations.CreateModel(
            name='TrendingVendors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=220)),
                ('business_name', models.CharField(max_length=120)),
                ('business_profile_pic', models.ImageField(upload_to='business_profile_pic')),
            ],
        ),
    ]
