# Generated by Django 5.1.5 on 2025-01-27 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hallwaywebsite', '0005_generalarticle_hallwayevents_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hallwayevents',
            old_name='header_img',
            new_name='flyer_img',
        ),
    ]
