# Generated by Django 5.1.5 on 2025-01-27 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hallwaywebsite', '0006_rename_header_img_hallwayevents_flyer_img'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HallwayEvents',
            new_name='HallwayEvent',
        ),
        migrations.RenameModel(
            old_name='TopPerformingProfessionals',
            new_name='TopPerformingProfessionalArticle',
        ),
        migrations.RenameModel(
            old_name='TrendingVendors',
            new_name='TrendingVendorArticle',
        ),
    ]
