# Generated by Django 5.1.5 on 2025-01-27 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hallwaywebsite', '0010_alter_hallwayevent_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hallwayevent',
            name='time',
            field=models.CharField(max_length=50),
        ),
    ]
